---
title: "play"
output: html_notebook
---

Aim: display livescore output in same order as livescore (down left side)

## packages

```{r}
library(tidyverse)
library(rvest)
```

## functions

```{r}
score_table=function(html) {
  html %>% html_nodes('body > div > div.content') %>% html_nodes('div')  -> dd
  dd %>% html_attr('class') -> classes
  dd %>% html_text() -> texts
  tibble(class=classes,text=texts) %>% 
    mutate(title=ifelse(class=="left",text,NA)) %>% fill(title) %>% 
    separate(title, into=c("country", "league"), sep="-") %>% 
    filter(str_detect(class,"row-gray")) -> d4
  m=str_split(d4$text,"  ",simplify=T)
  d4 %>% mutate(mins=m[,2],t1=m[,3],score=m[,4],t2=m[,5]) %>% 
    filter(str_length(mins)<=10) %>% 
    select(-(class:text))
}

update_scores=function(my_url) {
  html_new=read_html(my_url)
  d_new=score_table(html_new)
  d_new %>% mutate(timestamp=Sys.time(),key=str_c(t1," - ",t2))
}

```

## get some html

```{r}
my_url="http://www.livescores.com/soccer/live"
# update_scores(my_url) %>% separate(title, into=c("country", "league"), sep="-")
html=read_html(my_url)
score_table(html)
```

## the countries down the left

this appears to work. Now I want the countries down the left, in the order that they are.

```{r}
my_url="http://www.livescores.com"
html=read_html(my_url)
html %>% html_nodes("a.cat") %>% html_text()
```

